apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      nodeSelector: 
        disk: ssd # selector node have label disk=ssd. for example node is labeled by: kubectl label nodes <your-node-name> disk=ssd
      containers:
        - name: main
          image: luksa/ssd-monitor
